### ISSUE TITLE
Question: Register Plugin in OctoPrint

### ISSUE THREAD

**Issue by cromlegionar** [jneilliii/OctoPrint-Playlist#13]
Hello, 

I am sorry if this is the wrong place, but I wondered why this plugin isn't registered in the official octoprint plugin list?
I am in need of a plugin very much like this one, and I am looking into writing one atm but if it turns out I can use this one for my purpose I would contribute to it.
But I would like for it to be officially supported by octoprint (and it's standards), therefore asking this question here. :)

**Comment by jneilliii** [comment]
The main reason I didn't register the plugin officially was because it monkey patches the communication layer and I know that there is a huge re-write of that underway now. I at one point did try to register but closed it for these reasons. There was some discussion in the pull request [here](https://github.com/OctoPrint/plugins.octoprint.org/pull/477) that discusses possibly alternatives, but I haven't had any big push for updating yet since I don't use the plugin. I would be completely open to accepting PRs that get around the monkey patching and re-submit to the plugin repository if I don't get around to it. 

An alternative plugin that is similar would be the continuous print plugin. Maybe that one could also fill your needs.
